export default [
  {
    id: 'Task 01',
    title: 'Deliver Challenge',
    image: 'https://avatars1.githubusercontent.com/u/25140387?s=460&v=4',
    priority: 'high',
    deadlineDate: '22/04',
    deadlineTime: '21:30',
  },
  {
    id: 'Task 02',
    title: 'App Interface',
    image: 'https://assets.rbl.ms/14779241/980x.jpg',
    priority: 'medium',
    deadlineDate: '22/04',
    deadlineTime: '10:30',
  },
  {
    id: 'Task 03',
    title: 'Schedule Meeting',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8dFqz46O2LS1pyiyW9jMDEhmomrksJHzmaQy35j7bRbYLchyJcQ',
    priority: 'high',
    deadlineDate: '22/04',
    deadlineTime: '17:00',
  },
  {
    id: 'Task 04',
    title: 'Buy Groceries',
    image: 'https://avatars3.githubusercontent.com/u/30187750?s=460&v=4',
    priority: 'medium',
    deadlineDate: '23/04',
    deadlineTime: '14:45',
  },
  {
    id: 'Task 05',
    title: 'Eat Yogurt',
    image: 'https://timedotcom.files.wordpress.com/2017/12/terry-crews-person-of-year-2017-time-magazine-2.jpg',
    priority: 'low',
    deadlineDate: '23/04',
    deadlineTime: '12:00',
  },
  {
    id: 'Task 06',
    title: 'Read a Book',
    image: 'https://assets.rbl.ms/14779241/980x.jpg',
    priority: 'low',
    deadlineDate: '24/04',
    deadlineTime: '21:00',
  },
  {
    id: 'Task 07',
    title: 'Attend to Court',
    image: 'https://avatars3.githubusercontent.com/u/30187750?s=460&v=4',
    priority: 'high',
    deadlineDate: '24/04',
    deadlineTime: '9:30',
  },
  {
    id: 'Task 08',
    title: 'Buy a car',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8dFqz46O2LS1pyiyW9jMDEhmomrksJHzmaQy35j7bRbYLchyJcQ',
    priority: 'medium',
    deadlineDate: '24/04',
    deadlineTime: '13:40',
  },
  {
    id: 'Task 09',
    title: 'Workout',
    image: 'https://timedotcom.files.wordpress.com/2017/12/terry-crews-person-of-year-2017-time-magazine-2.jpg',
    priority: 'low',
    deadlineDate: '25/04',
    deadlineTime: '21:30',
  },
];
